### ISSUE TITLE
importBC_data() - suggestion: load 'plyr' before 'dplyr'

### ISSUE THREAD

**Issue by GailR** [bcgov/envair#5]
I noticed that `dplyr::group_by()`wasn't working for me after using the `importBC_data()` function. 

Loading the package `plyr` before `dplyr` will prevent this type of issue. See previous discussion on this topic [here](https://stackoverflow.com/questions/31644739/loading-dplyr-after-plyr-is-causing-issues).

The following change to `importBC_data()` (line 46) should do the trick:
**Current**
#load packages
  RUN_PACKAGE(c('dplyr','RCurl','plyr','readr','lubridate','tidyr','stringi'))  #,'feather'
  if (is.null(years))
  {
    years=as.numeric(format(Sys.Date(),'%Y'))
  }

**Update to**
#load packages
  RUN_PACKAGE(c('plyr', 'dplyr', 'RCurl', 'readr', 'lubridate', 'tidyr' ,'stringi'))  #,'feather'
  if (is.null(years))
  {
    years=as.numeric(format(Sys.Date(),'%Y'))
  }

**Or use [tidyverse](https://tidyverse.tidyverse.org)** (which includes several packages listed above)
#load packages
  RUN_PACKAGE(c('plyr', 'RCurl', 'stringi', 'tidyverse',  'lubridate'))  #,'feather'
  if (is.null(years))
  {
    years=as.numeric(format(Sys.Date(),'%Y'))
  }

**Comment by ateucher** [comment]
Hope you don't mind me chiming in here! It's not considered good practice to load libraries in a package (in fact if you tried to upload to CRAN they won't allow it). The reason is that it is altering the user's environment in ways that they have not asked for, and is considered "user-hostile" (perhaps a bit harsh, but @GailR's experience proves the point).

Instead you should list all of the packages that `envair` uses in the `Imports:` field in the `DESCRIPTION` file. That ensures that all of the packages will be installed and available for your package to use. It looks like you normally specify the functions using the `package::function()` syntax, which is great - that is how you call a function without loading the package using `library()` or `require()`. So by listing the dependencies in the `DESCRIPTION` you will ensure the required packages are installed, and then using the `package::function()` you can call all the functions you need without loading the libraries.

Some useful links:
https://r-pkgs.org/description.html#dependencies
https://r-pkgs.org/namespace.html

Hope this is helpful!

**Comment by aseagram** [comment]
+1 upvote to have this issue fixed ASAP, as described above. @jeromerobles

**Comment by jeromerobles** [comment]
New version (envair 0.1.0.0), now removes the loading of libraries
